### ISSUE TITLE
Erro: unmapped2anchors.py: error: no such option: -Q

### ISSUE THREAD

**Issue by Alipe2021** [egaffo/circompara2#3]
When I  run the command `circompara2` it reported an error:

```
BYPASS = ['linear']: skipping linear transcript analysis
scons: done reading SConscript files.
scons: Building targets ...
unmapped2anchors.py -Q <( zcat samples/CK_BML1234_00h1/processings/circRNAs/CK_BML1234_00h1.unmappedSE.fq.gz ) | bowtie2 --seed 123 -p 16 --reorder --score-min=C,-15,0 -q -x /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/Bowtie2Index/genome.fa -U - 2> samples/CK_BML1234_00h1/processings/circRNAs/find_circ_out/bt2_secondpass.log | find_circ.py -G /MaizeLab/auhpc1/DataBase/Species/Zea_Mays/B73v4/zma_dna_v4.fa -p CK_BML1234_00h1_ -s samples/CK_BML1234_00h1/processings/circRNAs/find_circ_out/find_circ.log -R samples/CK_BML1234_00h1/processings/circRNAs/find_circ_out/sites.reads > samples/CK_BML1234_00h1/processings/circRNAs/find_circ_out/sites.bed
Usage:

  unmapped2anchors.py <alignments.bam> > unmapped_anchors.qfa

Extract anchor sequences from unmapped reads. Optionally permute.


unmapped2anchors.py: error: no such option: -Q
Traceback (most recent call last):
  File "/opt/biosoft/find_circ-1.2/find_circ.py", line 608, in <module>
    sam = pysam.Samfile('-','r')
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 990, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

gzip: stdout: Broken pipe
scons: *** [samples/CK_BML1234_00h1/processings/circRNAs/find_circ_out/sites.bed] Error 1
scons: building terminated because of errors.
```

**Comment by egaffo** [comment]
are you using the Docker container or did you install CirComPara2 in your environment?

**Comment by Alipe2021** [comment]
I install CirComPara2 in a conda environment by the following steps：
```sh
conda create -n circompara2_py2_env -c conda-forge python=2.7
conda install -n circompara2_py2_env -c bioconda samtools bedtools hisat2 star
conda install -n circompara2_py2_env -c bioconda segemehl
source  activate circompara2_py2_env
git clone http://github.com/egaffo/circompara2
cd circompara2/
./src/utils/bash/install_circompara
```

**Comment by egaffo** [comment]
Unfortunately, I was not able to reproduce your error. 
I installed circompara2 following your installation procedure and the circompara2 test run ended successfully.
Your error is quite weird. It seems that the unmapped2anchors.py script of the Find_circ tool ([https://github.com/marvin-jens/find_circ](https://github.com/marvin-jens/find_circ)) does not recognize its option :\ 
Moreover, it seems that there is an error in find_circ.py
Please, make sure you are running the Find_circ scripts installed with the circompara2 installation procedure (I see a call to /opt/biosoft/find_circ-1.2/find_circ.py, which appears not to be in the circompara2 directory).
Another check is related to the input FASTQ: check if the samples/CK_BML1234_00h1/processings/circRNAs/CK_BML1234_00h1.unmappedSE.fq.gz is not actually an empty file or not a FASTQ (GZIP compressed)

**Comment by Alipe2021** [comment]
I tested the unmapped2anchors.py program, but i can't find the param '-Q':

<img width="568" alt="图片" src="https://user-images.githubusercontent.com/77709930/145132549-2ac450f0-3652-4067-87cd-b5a52ef63b67.png">

**Comment by egaffo** [comment]
You are calling an older version of find_circ (v1), possibly from some instance in your environment. 
Update it to v1.2 [https://github.com/marvin-jens/find_circ/releases/tag/v1.2](https://github.com/marvin-jens/find_circ/releases/tag/v1.2), it has the -Q option.

**Comment by Alipe2021** [comment]
Thanks. I upgraded the unmapped2anchors.py from the github master branch and solved it.
