### ISSUE TITLE
scons: warning: Two different environments were specified for target SRR5388395_1_fastqc.html

### ISSUE THREAD

**Issue by mianlee** [egaffo/circompara2#5]
Dear author：

I was running circompara2 on CentOS 7 by docker.

Here is my var.py and run command :  "docker run -u `id -u` --rm -it -v $(pwd):/data egaffo/circompara2:v0.1.2.1"

$ cat vars.py

META            = 'meta.csv'
CPUS            = '4'
**## pre-computed index and annotation files**
GENOME_FASTA="genome_indexes/human_ref/GRCh38.fa"
GENOME_INDEX="genome_indexes/indexes/hisat2/GRCh38"
SEGEMEHL_INDEX="genome_indexes/indexes/segemehl/GRCh38.idx"
BWA_INDEX="genome_indexes/indexes/bwa/GRCh38"
BOWTIE2_INDEX="genome_indexes/indexes/bowtie2/GRCh38"
BOWTIE_INDEX="genome_indexes/indexes/bowtie/GRCh38"
STAR_INDEX="genome_indexes/indexes/star/GRCh38"
GENEPRED="genome_indexes/annotation/GRCh38.genePred.wgn"
ANNOTATION="genome_indexes/human_ref/GRCh38.gtf"

PREPROCESSOR    = 'trimmomatic'
PREPROCESSOR_PARAMS = 'MAXINFO:40:0.5 LEADING:20 TRAILING:20 SLIDINGWINDOW:4:30 MINLEN:35 AVGQUAL:30'

I am getting the following warnings: 

scons: Reading SConscript files ...

scons: warning: Two different environments were specified for target SRR5388395_1_fastqc.html,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1_fastqc.zip,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fastq_fastqc.log,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fastq_fastqc.err,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1_fastqc/fastqc_data.txt,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.P.qtrim_fastqc.html,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.P.qtrim_fastqc.zip,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.P.qtrim_fastqc.log,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.P.qtrim_fastqc.err,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.P.qtrim_fastqc/fastqc_data.txt,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.U.qtrim_fastqc.html,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.U.qtrim_fastqc.zip,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.U.qtrim_fastqc.log,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.U.qtrim_fastqc.err,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>

scons: warning: Two different environments were specified for target SRR5388395_1.fq.U.qtrim_fastqc/fastqc_data.txt,
	but they appear to have the same action: echo "No reads in ${SOURCES[0]}" > ${TARGETS[0]} && echo "No reads in ${SOURCES[0]}" > ${TARGETS[4]} && fastqc $SOURCE -o ${TARGETS[0].dir} --extract > ${TARGETS[2]} 2> ${TARGETS[3]} 
File "/circompara2/src/sconstructs/fastqc.py", line 66, in <module>
scons: done reading SConscript files.
scons: Building targets ...

Is this matters ? 

Question 2: How can I specify -j 2 using docker image ?

Thank you so much for your time.

**Comment by egaffo** [comment]
Q1:
I do not understand your message, I see strikethrough text...could you please clean it leaving only relevant text?
Please, check the name of the files in your meta.csv, it seems CirComPara2 is reading twice the same source.
Perhaps you forgot to rename SRR5388395_1 into SRR5388395_2 in a copying&pasting?

Q2:
Just append it to the command line, e.g.:
``docker run -u `id -u` --rm -it -v $(pwd):/data egaffo/circompara2:v0.1.2.1 -j 2``

**Comment by mianlee** [comment]
Hello @egaffo， 

Thank you so much for your kind reply. I really appreciated it.

1. Sorry for my bad markdown editing and I fixed that. 
2. I stayed up late last night and You were right I forgot to rename SRR5388395_1 into SRR5388395_2 in a copying&pasting, bad mistake.
3. Ok, I got it !

I finally got the pipeline worked using docker image. Thank you for your help !!
